apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_MONGODB_SERVER: "mongodb"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
